openapi: 3.0.0
info:
  title: 'Laravel RESTful APIs'
  description: 'Example of RESTful APIs'
  contact:
    email: saad-amjad@monstar-lab.com
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
    description: 'Demo API Server'
paths:
  /api/v1/books:
    get:
      tags:
        - Books
      summary: 'Get list of books'
      description: 'Returns list of books'
      operationId: index
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookCollection'
        401:
          description: Unauthenticated
        403:
          description: Forbidden
      security:
        -
          apiAuth: []
components:
  schemas:
    BookCollection:
      title: 'Book Collection'
      description: 'Book Collection'
      properties:
        data:
          title: Data
          description: 'Data wrapper'
          type: array
          items:
            $ref: '#/components/schemas/BookResource'
      type: object
      xml:
        name: BookCollection
    BookResource:
      title: 'Book Resource'
      description: 'Book resource'
      properties:
        id:
          title: ID
          description: ID
          type: integer
          format: int64
          example: 1
        title:
          title: Title
          description: 'Name of the new book'
          type: string
          example: 'A nice project'
        created_at:
          title: 'Created at'
          description: 'Created at'
          type: string
          format: datetime
          example: '2020-01-27 17:50:45'
        updated_at:
          title: 'Updated at'
          description: 'Updated at'
          type: string
          format: datetime
          example: '2020-01-27 17:50:45'
        author_id:
          title: 'Author ID'
          description: 'Author''s id of the new project'
          type: integer
          format: int64
          example: 1
      type: object
      xml:
        name: BookResource
  securitySchemes:
    apiAuth:
      type: http
      description: 'A short description for security scheme'
      name: 'Token Based '
      scheme: bearer
      in: header
tags:
  -
    name: Books
    description: 'API Endpoints of Books'
security:
  - []
